### ISSUE TITLE
Which command to use?

### ISSUE THREAD

**Issue by andersgs** [peterk87/sistr_cmd#12]
In `Usage` it appears as `predict_serovar`, while in `Example` it appears as `sistr`. From `setup.py` I am guessing `sistr`.

That said, it is a very useful piece of software. Thank you!!!

Anders.

**Comment by peterk87** [comment]
Glad that the program is useful for you!

The naming issue should be resolved in the `master` branch.

```
pip install git+https://github.com/peterk87/sistr_cmd.git@master
```
