### ISSUE TITLE
Will you put this in 'pip' ?

### ISSUE THREAD

**Issue by tseemann** [peterk87/sistr_cmd#5]
Do you think you could make this pip installable?

In terms of writing a Brew or Conda package for it, would hate to waste effort now.

**Comment by peterk87** [comment]
I think that might be a good idea if people find `sistr_cmd` useful.

**Comment by tseemann** [comment]
The world is looking for easy non-web, high-throughput trustworthy tools to put into pipelines. If you put it in pip, you will get good uptake. Salmonella is the most sequenced organism in public health micro and no one wants to do serotyping anymore!
