### ISSUE TITLE
Multiple input file support

### ISSUE THREAD

**Issue by tseemann** [peterk87/sistr_cmd#7]
For CSV output you get 2 rows: 1 header and 1 data.

It would be cool if you could give `sistr` multiple FASTA files and get a CSV 'spreadsheet' of the results.

eg. `sistr -i <file_of_filenames>`  or `sistr *.fasta`

**Comment by peterk87** [comment]
I was thinking about adding support for that. 

Right now I just use GNU Parallel, output some JSON and use a simple Python script to stitch everything together into a larger output file:

```
parallel python sistr_cmd.py -i {} -o out/{.}.json ::: salmonella/*.fasta
```

Script/IPython Notebook code might be something like this:

```python
import pandas as pd
import json
import os

jsons = [x for x in os.listdir('out/') if '.json' in x]
dicts = [json.load(open(x)) for x in jsons]
df = pd.DataFrame(dicts)
df.to_csv('out.csv')
```

Do you recommend any good/simple parallel/async execution library?

I use [Celery](https://celery.readthedocs.io/en/latest/index.html) for the SISTR web app. I don't think that would be appropriate for what should be a simple script.

**Comment by tseemann** [comment]
I used `parallel` just as you did above :-)

Within python I guess the standard approach is `multiprocessing` library:
https://docs.python.org/2/library/multiprocessing.html

If you want to be smarter about it and support cluster queuing systems easily then 'drmaa':
http://drmaa-python.readthedocs.io/en/latest/
