### ISSUE TITLE
Tag a release

### ISSUE THREAD

**Issue by tseemann** [peterk87/sistr_cmd#8]
It would be good if you could tag an official release for Brew / Conda packaging etc.

Maybe once the previous Issues are sorted out.

**Comment by peterk87** [comment]
So you should be able to install `sistr_cmd` from PyPI with:

```bash
pip install sistr-cmd
```

I've tagged a release for v0.1.1:

https://github.com/peterk87/sistr_cmd/releases/tag/0.1.1 

I haven't used Linux/Homebrew, but I have used `pip` within a Conda Python env.

**Comment by peterk87** [comment]
``sistr_cmd`` can be installed using Conda through the BioConda channel:

https://bioconda.github.io/recipes/sistr_cmd/README.html
